# Dockerfile for NGINX

# Use the official NGINX image as a base image
FROM nginx:latest

# Copy custom NGINX configuration file to the container
COPY nginx.conf /etc/nginx/nginx.conf

# Expose the port NGINX will run on
EXPOSE 80